#!/usr/bin/env bash
# This is a script that Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get install -y haproxy

# To configure HAProxy load balance 
echo "frontend http
	bind *:80
	mode http
	default_backend web-backend
    backend web-backend
	balance roundrobin
	server 6931-web-01 54.167.186.166:80 check
	server 6931-web-02 34.227.152.242:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable HAProxy to be started by the init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart