#!/usr/bin/env bash
# Transfers a file to a remote server

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH="$1"
IP="$2"
USER="$3"
KEY="$4"

scp -o StrictHostKeyChecking=no -i "$KEY" "$FILE_PATH" "${USER}@${IP}:~/"
