#!/usr/bin/env bash
# A script Configure your Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '/server_name _/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

echo "server {
    listen 80;
    server_name _;

    error_page 404 /custom_404.html;

    location / {
        root /var/www/html;
    }

    location = /custom_404.html {
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
