#!/usr/bin/env bash
# Configure Nginx to have a custom 404 page that contains the string "Ceci n'est pas une page"

sudo apt-get -y update
sudo apt-get -y install nginx

# Create the main page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Create the custom 404 page in the same root directory
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Overwrite Nginx default server block
echo "server {
    listen 80;
    listen [::]:80;

    server_name thewaliyatbadmus.tech www.thewaliyatbadmus.tech;

    root /var/www/thewaliyatbadmus.tech/html;
    index index.html;

    error_page 404 /custom_404.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Test and restart Nginx
sudo nginx -t
sudo systemctl restart nginx || sudo service nginx restart